# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2

# We use the machine executor because our dev_db.sh uses docker to run
# a fixed postgres version. Additionally, if we wanted to use docker
# for builds we'd need to setup a custom lein+npm+postgres image and
# publish it on docker hub. Maybe some day.

defaults: &defaults
  machine:
    image: ubuntu-1604:201903-01
  working_directory: ~/repo
  environment:
    LEIN_ROOT: "true"
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      # upgrade node
      # TODO: could upgrade node using NVM but it seems poorly documented and a hassle
      - run: sudo rm /opt/circleci/.nvm/versions/node/v6.1.0/bin/node
      - run: curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
      - run: sudo apt install nodejs

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
            # node_modules won't pick up updates to sub dependencies
            # unless the project.clj is changed. This might create differences
            # between dev, CI and actual deployment.
            - node_modules
          key: v2-dependencies-{{ checksum "project.clj" }}

  without-db:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "project.clj" }}
      # verify that we can run unit tests without the database:
      - run: DATABASE_URL=invalid lein kaocha --reporter kaocha.report/documentation unit

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "project.clj" }}
      # killall is a workaround for apt failing with: Could not get lock /var/lib/apt/lists/lock
      - run: sudo killall -9 apt-get || true; sudo apt update

      # upgrade chromedriver and node
      - run: sudo apt remove google-chrome-stable
      # remove conflicting versions installed by circle
      # TODO: could upgrade node using NVM but it seems poorly documented and a hassle
      - run: sudo rm /usr/local/bin/chromedriver /opt/circleci/.nvm/versions/node/v6.1.0/bin/node
      - run: curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
      - run: sudo apt install chromium-chromedriver nodejs

      - run: FOR_TESTS=1 ./dev_db.sh
      - run: lein cljtests-ci
      - store_artifacts:
          path: browsertest-errors

  doo:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "project.clj" }}
      - run: lein doo chrome-headless test once

  war:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "project.clj" }}
      - run: lein uberwar
      - store_artifacts:
          path: target/uberjar/rems.war
      - run: lein uberjar
      - store_artifacts:
          path: target/uberjar/rems.jar
      - run: docker build --pull --tag rems .
      # TODO: actual docker repo url
      - run: ./.circleci/docker-release.sh rems example.com/repo

  # pseudo job to post a single ok status to github after all the tests
  ok:
    executor: docker
    docker:
      - image: alpine
    steps:
      - run: 'true'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - without-db:
          requires:
            - build
      - test:
          requires:
            - build
      - doo:
          requires:
            - build
      - war:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - ok:
          requires:
            - build
            - without-db
            - test
            - doo
            - war
